# Generated by Django 2.2.6 on 2020-01-15 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orient_advances', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={},
        ),
        migrations.RenameField(
            model_name='section',
            old_name='Section name',
            new_name='section_name',
        ),
    ]
