# Generated by Django 2.2.6 on 2020-02-10 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orient_advances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='other',
            name='emplyee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='other',
            name='expens_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orient_advances.Expens'),
        ),
        migrations.AddField(
            model_name='advance',
            name='emplyee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
