# Generated by Django 2.2.6 on 2020-02-05 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orient_advances', '0002_advance_emplyee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount should be in LE', max_digits=7)),
                ('request_date', models.DateField(default='2018-1-1')),
                ('description', models.TextField(null=True)),
                ('emplyee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
