# Generated by Django 2.2.6 on 2020-02-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orient_advances', '0003_other'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expens_name', models.CharField(max_length=40, unique=True)),
            ],
        ),
    ]
