# Generated by Django 3.0.2 on 2020-01-22 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orient_advances', '0003_advance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advance',
            name='Advance Date',
        ),
        migrations.RemoveField(
            model_name='advance',
            name='Advance amount',
        ),
        migrations.RemoveField(
            model_name='advance',
            name='emplyee',
        ),
        migrations.AddField(
            model_name='advance',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount should be in LE', max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advance',
            name='emplyee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advance',
            name='request_date',
            field=models.DateField(default='2018-1-1'),
            preserve_default=False,
        ),
    ]
