# Generated by Django 3.0.2 on 2020-01-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orient_advances', '0004_auto_20200122_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advance',
            name='request_date',
            field=models.DateField(default='2018-1-1'),
        ),
    ]
