# Generated by Django 2.2.6 on 2020-02-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='fullname',
            field=models.CharField(default='Please change your name', max_length=90),
            preserve_default=False,
        ),
    ]
