# Generated by Django 2.2.6 on 2020-01-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_auto_20200115_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='employee_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
