# Generated by Django 2.2.6 on 2020-01-15 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_auto_20200116_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='section',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='orient_advances.Section'),
        ),
    ]
