# Generated by Django 2.2.6 on 2020-01-15 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_auto_20200116_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='employee_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orient_advances.Section'),
        ),
    ]
