# Generated by Django 2.2.6 on 2020-01-16 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_auto_20200116_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='section',
        ),
    ]
