# Generated by Django 2.2.6 on 2020-01-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_remove_profile_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='employee_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
